"""Where `generated/contracts.py` reads the frozen `contracts/` schema files from.

Kept in its own module, deliberately separate from `generated/contracts.py`, because that file
is wholly regenerated by `scripts/codegen.mjs` on every `pnpm codegen` run (see its
`generatePython()`) — override logic hand-written directly into a generated file would be
silently discarded the next time codegen runs, with no error and no warning. This module is not
generated and codegen never touches it, so it is the one place the `$PBFUZZ_CONTRACTS_DIR`
override lives; `generatePython()` emits `from .. import _contracts_dir` and
`_SCHEMA_DIR = _contracts_dir.schema_dir()` into every regenerated `generated/contracts.py`, so
the override survives regeneration with no hand-patching needed.

Was the old CC hook layer's `engine/hooks/pbfuzz_hooks/schema.py::find_contracts_dir`'s
`$PBFUZZ_CONTRACTS_DIR` convention (same env var, same "explicit override wins outright"
precedence) — that tree is gone; this module is now the only place the convention lives.
"""

from __future__ import annotations

import os
from pathlib import Path

#: `generated/contracts.py`'s own default, recomputed relative to THIS file's location instead
#: (`_contracts_dir.py` sits one directory above `generated/`, so it is `parents[2]`, not
#: `generated/contracts.py`'s `parents[3]`, that lands on the repo root):
#: `pbfuzz_engine/ -> engine/ -> <repo root>/contracts`.
_DEFAULT_SCHEMA_DIR = Path(__file__).resolve().parents[2] / "contracts"


def schema_dir() -> Path:
    """The contracts directory `generated/contracts.py::load_schema` should read from.

    `$PBFUZZ_CONTRACTS_DIR`, if set, wins outright — used by tests and by any deployment that
    installs the contracts somewhere other than next to the engine checkout. There is
    deliberately no existence check here: an override that points nowhere should fail loudly
    at the first `load_schema()` call (a clear `FileNotFoundError`), not silently fall back to
    a directory the caller did not ask for.
    """
    env = os.environ.get("PBFUZZ_CONTRACTS_DIR")
    return Path(env) if env else _DEFAULT_SCHEMA_DIR
