"""The primary tracer: gdb driven through its Python API in batch mode.

One traced run is one ``gdb -batch -x script.py`` invocation. There is no
interactive session, no FIFO and no DAP adapter: the script sets the
breakpoints, lets gdb auto-continue through them, and writes a JSON report that
this module parses. Everything that can be tested without gdb — building the
script, building the run line, parsing the report, parsing ``info breakpoints``
— is a pure function here.

Breakpoints are created with ``set breakpoint pending on``, so a line gdb
cannot bind becomes a *pending* breakpoint rather than an error, and is
reported as ``resolved: false``. That distinction is the whole point: zero hits
on a bound breakpoint means "not executed", while an unbound breakpoint means
"the build has no line info for this location" and has different remedies.

:module: pbfuzz_engine.tracers.gdb_batch
"""

from __future__ import annotations

import json
import os
import re
import shlex
import tempfile
from pathlib import Path
from typing import Any, Mapping, Sequence

from .base import (
    Breakpoint,
    BreakpointReport,
    HitRecord,
    InlineValue,
    Remedy,
    TargetCommand,
    TraceResult,
    Tracer,
    TracerError,
    build_command,
    which,
)

__all__ = [
    "GdbBatchTracer",
    "FLUSH_INTERVAL_SEC",
    "build_gdb_script",
    "build_run_command",
    "parse_info_breakpoints",
    "parse_trace_report",
]

# N2: hits are batched into a periodic flush at most this often, rather than
# one os.replace() per hit (the original ~120 hits/sec ceiling). Exposed as a
# real module constant -- not just a literal baked into the generated script
# text -- so tests can compute an exact expected flush bound instead of
# duplicating the number.
FLUSH_INTERVAL_SEC = 0.25

# gdb prints pending breakpoints in `info breakpoints` with <PENDING> in the
# address column; a bound one shows an address or a source location.
_INFO_BP_ROW = re.compile(
    # Num  Type  Disp  Enb  Address
    r"^(?P<num>\d+)\s+\S+\s+\S+\s+\S+\s+(?:(?P<pending><PENDING>)|(?P<addr>\S+))",
    re.MULTILINE,
)


def build_run_command(cmd: TargetCommand, stderr_path: str) -> str:
    """Build gdb's ``run`` line, with the program's own stdio redirected.

    The program's stderr must not mix into gdb's, because the oracle matches
    ``reached``/``triggered`` patterns against the *program's* stderr. gdb
    starts the inferior under a shell on Linux, so shell redirections work.
    """
    parts = ["run"]
    parts.extend(shlex.quote(a) for a in cmd.argv[1:])
    if cmd.stdin_path:
        parts.append("< " + shlex.quote(cmd.stdin_path))
    parts.append("2> " + shlex.quote(stderr_path))
    return " ".join(parts)


def build_gdb_script(spec_path: str, out_path: str) -> str:
    """Return the gdb-Python batch script source.

    The script is deliberately self-contained and reads its work from
    ``spec_path`` so nothing has to be escaped into the source text. Hits are
    batched into a periodic flush (N2: at most once every
    ``FLUSH_INTERVAL_SEC``) rather than one ``os.replace`` per hit, which was
    the throughput ceiling on a hot breakpoint; every other transition
    (process exit, a fatal signal, and the final teardown) still forces an
    immediate flush, so a run killed by the outer timeout never loses more
    than one interval's worth of the evidence collected up to that point.
    """
    return _GDB_SCRIPT_TEMPLATE.format(
        spec_path=json.dumps(spec_path),
        out_path=json.dumps(out_path),
        flush_interval=repr(FLUSH_INTERVAL_SEC),
    )


_GDB_SCRIPT_TEMPLATE = '''\
# Generated by pbfuzz_engine.tracers.gdb_batch — do not edit.
import json
import os
import time
import traceback

import gdb

SPEC_PATH = {spec_path}
OUT_PATH = {out_path}

with open(SPEC_PATH) as _f:
    SPEC = json.load(_f)

REPORT = {{
    "breakpoints": [
        {{
            "location": bp["location"],
            "function": None,
            "resolved": None,
            "hit_times": 0,
            "hits": [],
            "number": None,
        }}
        for bp in SPEC["breakpoints"]
    ],
    "signal": None,
    "exit_code": None,
    "errors": [],
    "info_breakpoints": "",
    "flush_count": 0,
}}
_ORDER = [0]

# N2: a plain per-hit flush caps a hot breakpoint at roughly one os.replace()
# syscall per hit (~120 hits/sec measured pre-fix). Batching hits into a
# periodic flush removes that ceiling; every non-hot-path transition below
# still calls _flush(force=True) so evidence is never more than one interval
# stale when the run is killed. Value comes from the real
# pbfuzz_engine.tracers.gdb_batch.FLUSH_INTERVAL_SEC constant (formatted in
# below), not a separately-maintained literal.
_FLUSH_INTERVAL_SEC = {flush_interval}
_LAST_FLUSH_MONO = [0.0]


def _flush(force=False):
    # Write to a temp file in the same directory, then atomically replace the
    # real path (os.replace is a single rename(2) on the same filesystem). A
    # plain `open(OUT_PATH, "w")` truncates in place, so a SIGKILL landing
    # mid-write left a corrupted/empty file; os.replace can only ever leave
    # the OLD complete content or the NEW complete content, never a partial
    # mix. `force=False` throttles this to at most once per
    # _FLUSH_INTERVAL_SEC (N2); callers that need the report to reflect the
    # very latest state right now (process exit, a fatal signal, teardown)
    # pass force=True.
    now = time.monotonic()
    if not force and (now - _LAST_FLUSH_MONO[0]) < _FLUSH_INTERVAL_SEC:
        return
    _LAST_FLUSH_MONO[0] = now
    REPORT["flush_count"] += 1
    tmp_path = OUT_PATH + ".tmp"
    try:
        with open(tmp_path, "w") as fh:
            json.dump(REPORT, fh)
            fh.flush()
        os.replace(tmp_path, OUT_PATH)
    except Exception:
        pass


def _safe(cmd):
    try:
        return gdb.execute(cmd, to_string=True)
    except Exception as exc:  # pragma: no cover - gdb-side
        REPORT["errors"].append("%s: %s" % (cmd, exc))
        return ""


class _Bp(gdb.Breakpoint):
    def __init__(self, index, spec):
        self._index = index
        self._spec = spec
        gdb.Breakpoint.__init__(self, spec["location"], gdb.BP_BREAKPOINT)

    def stop(self):
        rec = REPORT["breakpoints"][self._index]
        try:
            _ORDER[0] += 1
            rec["hit_times"] += 1
            rec["resolved"] = True
            frame = gdb.newest_frame()
            if rec["function"] is None:
                try:
                    rec["function"] = frame.name()
                except Exception:
                    rec["function"] = None
            hit = {{"order": _ORDER[0], "callstack": "", "inline_expr": []}}
            # A location gdb accepted may not be where it actually bound: a
            # line with no instruction (blank/comment-only) is silently
            # rebound to the next line that has one. `find_sal()` reports
            # where the hit *actually* landed, so it can be reported next to
            # the originally requested location instead of masquerading as it.
            try:
                sal = frame.find_sal()
                if sal is not None and sal.symtab is not None:
                    hit["resolved_location"] = "%s:%d" % (sal.symtab.filename, sal.line)
            except Exception:
                pass
            if self._spec.get("print_call_stack"):
                hit["callstack"] = _safe("bt").strip()
            for expr in self._spec.get("inline_expr") or []:
                try:
                    value = str(gdb.parse_and_eval(expr))
                except Exception as exc:
                    value = (
                        "<error: %s is not evaluable here (%s). How to fix: "
                        "1. check the variable is in scope at this line "
                        "2. set the breakpoint after the assignment>" % (expr, exc)
                    )
                hit["inline_expr"].append({{"name": expr, "value": value}})
            rec["hits"].append(hit)
            if rec["hit_times"] >= int(self._spec.get("hit_limit") or 10):
                self.enabled = False
        except Exception:
            REPORT["errors"].append(traceback.format_exc())
        _flush()
        return False  # never stop: this is a tracer, not a debugging session


def _on_exit(event):
    code = getattr(event, "exit_code", None)
    if code is not None:
        REPORT["exit_code"] = int(code)
    _flush(force=True)


def _on_stop(event):
    if isinstance(event, gdb.SignalEvent):
        REPORT["signal"] = str(getattr(event, "stop_signal", "") or "")
        _flush(force=True)


def _resolution(bp):
    locations = getattr(bp, "locations", None)
    if locations is not None:
        return len(locations) > 0
    pending = getattr(bp, "pending", None)
    if pending is not None:
        return not bool(pending)
    return None


def main():
    _safe("set confirm off")
    _safe("set pagination off")
    _safe("set height 0")
    _safe("set width 0")
    _safe("set backtrace limit %d" % int(SPEC.get("backtrace_limit") or 16))
    # Pending lets an unbindable location be REPORTED as unresolved instead of
    # aborting the script — the self-check depends on telling those apart.
    _safe("set breakpoint pending on")
    _safe("set disable-randomization on")

    created = []
    for index, bp_spec in enumerate(SPEC["breakpoints"]):
        try:
            bp = _Bp(index, bp_spec)
            REPORT["breakpoints"][index]["number"] = getattr(bp, "number", None)
            created.append((index, bp))
        except Exception as exc:
            REPORT["breakpoints"][index]["resolved"] = False
            REPORT["errors"].append("breakpoint %s: %s" % (bp_spec["location"], exc))

    for index, bp in created:
        REPORT["breakpoints"][index]["resolved"] = _resolution(bp)
    _flush(force=True)

    gdb.events.exited.connect(_on_exit)
    gdb.events.stop.connect(_on_stop)

    try:
        _safe(SPEC["run_command"])
    except Exception:
        REPORT["errors"].append(traceback.format_exc())

    # Re-read resolution AFTER the run: a breakpoint in a shared library only
    # binds once that library is loaded.
    for index, bp in created:
        state = _resolution(bp)
        if state is not None:
            REPORT["breakpoints"][index]["resolved"] = state
        if REPORT["breakpoints"][index]["hit_times"] > 0:
            REPORT["breakpoints"][index]["resolved"] = True
    REPORT["info_breakpoints"] = _safe("info breakpoints")
    _flush(force=True)
    try:
        gdb.execute("kill")
    except Exception:
        pass


try:
    main()
finally:
    _flush(force=True)
'''


def parse_info_breakpoints(text: str) -> dict[int, bool]:
    """Map gdb breakpoint number → resolved, from ``info breakpoints`` output.

    Used only as a fallback for gdb builds whose Python ``Breakpoint`` object
    exposes neither ``locations`` nor ``pending``.
    """
    out: dict[int, bool] = {}
    for match in _INFO_BP_ROW.finditer(text or ""):
        out[int(match.group("num"))] = match.group("pending") is None
    return out


def parse_trace_report(
    report: Mapping[str, Any],
    breakpoints: Sequence[Breakpoint],
    stderr: str = "",
    timed_out: bool = False,
) -> TraceResult:
    """Turn the gdb script's JSON report into a :class:`TraceResult`.

    Pure, and the reason a machine without gdb can still test the tracer: the
    fixtures under ``engine/tests/fixtures/tracers`` are reports of this shape.

    A hit's ``HitRecord.location`` is the debugger's *resolved* location
    (from ``hit["resolved_location"]`` when the script captured it), not
    necessarily the requested ``bp.location`` on ``BreakpointReport``: a
    breakpoint requested on a line with no code is silently rebound by
    gdb/lldb to the next line that has one, so the two can legitimately
    differ. Both are kept — the request is never overwritten.
    """
    info_resolution = parse_info_breakpoints(str(report.get("info_breakpoints") or ""))
    rows = list(report.get("breakpoints") or [])
    reports: list[BreakpointReport] = []
    for index, bp in enumerate(breakpoints):
        row: Mapping[str, Any] = rows[index] if index < len(rows) else {}
        resolved = row.get("resolved")
        if resolved is None:
            number = row.get("number")
            if isinstance(number, int):
                resolved = info_resolution.get(number)
        hit_times = int(row.get("hit_times") or 0)
        if hit_times > 0:
            resolved = True
        hits = [
            HitRecord(
                order=int(hit.get("order") or 0),
                callstack=str(hit.get("callstack") or ""),
                inline_expr=tuple(
                    InlineValue(name=str(v.get("name")), value=str(v.get("value")))
                    for v in (hit.get("inline_expr") or [])
                ),
                # `resolved_location`, when the debugger's own hit-time frame
                # info was captured, is where the breakpoint actually bound —
                # which can differ from the requested `bp.location` when a
                # no-code line got silently rebound to the next line that has
                # one. Fall back to the request for older report shapes.
                location=str(hit.get("resolved_location")) if hit.get("resolved_location") else bp.location,
            )
            for hit in (row.get("hits") or [])
        ]
        reports.append(
            BreakpointReport(
                location=bp.location,
                function=row.get("function") or None,
                resolved=None if resolved is None else bool(resolved),
                hit_times=hit_times,
                hits=hits,
            )
        )

    signal_name = report.get("signal") or None
    exit_code = report.get("exit_code")
    result = TraceResult(
        breakpoints=reports,
        signal=str(signal_name) if signal_name else None,
        exit_code=int(exit_code) if isinstance(exit_code, int) else None,
        timed_out=timed_out,
        stderr=stderr,
        tracer="gdb",
        diagnostics=[str(e) for e in (report.get("errors") or [])],
    )
    return result


def program_exists(program: str, cwd: str | None) -> bool:
    """Whether ``program`` (as `run()` is about to launch it) resolves to a real file.

    `entry.run_cmd` is written relative to `entry.cwd` (`./readelf @@`, the natural form for
    "run the binary the build produced") — `run()` itself gets this right, passing `cwd=cmd.cwd`
    straight to the subprocess. A bare `Path(program).exists()` does not: it resolves against
    *this process's* cwd, which is wherever the engine sidecar happened to start, not the
    campaign's. Found live in V1 (readelf-c): the target built and ran fine by hand, but the
    tracer reported `./readelf` "does not exist".
    """
    path = Path(program)
    if not path.is_absolute() and cwd:
        path = Path(cwd) / path
    return path.exists() or which(program) is not None


class GdbBatchTracer(Tracer):
    """Trace one run with ``gdb -batch``. The primary tracer for C/C++."""

    name = "gdb"
    languages = ("c", "cpp", "other")

    def __init__(self, gdb_path: str = "gdb") -> None:
        self.gdb_path = gdb_path or "gdb"

    def available(self) -> tuple[bool, str]:
        resolved = which(self.gdb_path)
        if not resolved:
            return False, f"`{self.gdb_path}` not found on PATH"
        code, out, err, _ = self._run_process(
            [resolved, "--version"], None, os.environ, 10.0
        )
        first = (out or err).splitlines()[0] if (out or err) else ""
        if code != 0:
            return False, f"`{resolved} --version` exited {code}: {err.strip()[:200]}"
        return True, f"{resolved}: {first}"

    def run(
        self,
        campaign: Mapping[str, Any],
        input_path: str,
        breakpoints: Sequence[Breakpoint],
        timeout_sec: float | None = None,
    ) -> TraceResult:
        gdb_bin = which(self.gdb_path)
        if not gdb_bin:
            raise TracerError(
                f"gdb was not found (`{self.gdb_path}`), so stage-1 runs cannot be traced.",
                [
                    Remedy(
                        id="install_gdb",
                        label="Install gdb",
                        detail="apt-get install gdb",
                        effect="run_command",
                    ),
                    Remedy(
                        id="set_gdb_path",
                        label="Point Settings → pbfuzz → execution.gdbPath at your gdb",
                        effect="manual",
                    ),
                    Remedy(
                        id="disable_tracer",
                        label="Set campaign `tracer: off` and run without breakpoint evidence",
                        effect="edit_campaign",
                    ),
                ],
            )
        bps = self._normalise(breakpoints)
        cmd = build_command(campaign, input_path)
        program = cmd.program
        if not program_exists(program, cmd.cwd):
            raise TracerError(
                f"The program to run does not exist: {program}",
                [
                    Remedy(
                        id="build_target",
                        label="Build the target first",
                        detail="`entry.run_cmd` points at a binary that is not there.",
                        effect="run_command",
                    )
                ],
            )

        with tempfile.TemporaryDirectory(prefix="pbfuzz-gdb-") as tmp:
            tmpdir = Path(tmp)
            spec_path = tmpdir / "spec.json"
            out_path = tmpdir / "report.json"
            stderr_path = tmpdir / "target-stderr.txt"
            stderr_path.touch()
            spec = {
                "program": program,
                "breakpoints": [b.to_spec() for b in bps],
                "run_command": build_run_command(cmd, str(stderr_path)),
                "backtrace_limit": 16,
            }
            spec_path.write_text(json.dumps(spec), encoding="utf-8")
            script_path = tmpdir / "pbfuzz_gdb_batch.py"
            script_path.write_text(
                build_gdb_script(str(spec_path), str(out_path)), encoding="utf-8"
            )

            argv = [
                gdb_bin,
                "-q",
                "-nx",
                "-batch",
                "-x",
                str(script_path),
                program,
            ]
            _, _, gdb_stderr, timed_out = self._run_process(
                argv, cmd.cwd, cmd.env, timeout_sec
            )

            report: dict[str, Any] = {}
            report_decode_error: str | None = None
            if out_path.exists():
                try:
                    report = json.loads(out_path.read_text(encoding="utf-8") or "{}")
                except json.JSONDecodeError as exc:
                    # With the atomic temp-file-then-os.replace flush, this should not
                    # happen for a report this module wrote — but stay defensive for an
                    # old-format or otherwise foreign leftover file, and say so instead
                    # of silently discarding whatever partial evidence was on disk.
                    report = {}
                    report_decode_error = str(exc)
            target_stderr = ""
            if stderr_path.exists():
                target_stderr = stderr_path.read_text(encoding="utf-8", errors="replace")

        if not report and not timed_out:
            detail = (gdb_stderr or "").strip()[:400] or None
            if report_decode_error:
                prefix = f"report file was present but not valid JSON ({report_decode_error}); "
                detail = prefix + (detail or "")
            raise TracerError(
                "gdb produced no trace report — it failed before the program ran.",
                [
                    Remedy(
                        id="inspect_gdb",
                        label="Run the gdb command by hand to see why",
                        detail=detail,
                        effect="manual",
                    )
                ],
            )
        result = parse_trace_report(report, bps, stderr=target_stderr, timed_out=timed_out)
        if report_decode_error:
            result.diagnostics.append(
                "gdb's report file existed but was not valid JSON, so it was treated as "
                f"empty (any partial evidence in it was lost): {report_decode_error}"
            )
        if gdb_stderr.strip():
            result.diagnostics.append(f"gdb stderr: {gdb_stderr.strip()[:400]}")
        return result
