"""The lldb tracer: same contract as gdb, driven with ``lldb --batch``.

The shape mirrors :mod:`pbfuzz_engine.tracers.gdb_batch` on purpose — a hook
module is generated, imported into lldb's own Python, sets the breakpoints with
script callbacks that never stop the process, and writes the same JSON report.
The report parser is shared with the gdb backend, so both are covered by the
same pure tests.

:module: pbfuzz_engine.tracers.lldb_batch
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Mapping, Sequence

from .base import Breakpoint, Remedy, TraceResult, Tracer, TracerError, build_command, which
from .gdb_batch import FLUSH_INTERVAL_SEC, parse_trace_report

__all__ = ["LldbBatchTracer", "build_lldb_hook", "build_lldb_argv"]


def build_lldb_hook(spec_path: str, out_path: str) -> str:
    """Return the Python module lldb imports to do the tracing.

    N2: hits are batched into a periodic flush (shares
    :data:`pbfuzz_engine.tracers.gdb_batch.FLUSH_INTERVAL_SEC` with the gdb
    backend) rather than one ``os.replace`` per hit.
    """
    return _LLDB_HOOK_TEMPLATE.format(
        spec_path=json.dumps(spec_path),
        out_path=json.dumps(out_path),
        flush_interval=repr(FLUSH_INTERVAL_SEC),
    )


_LLDB_HOOK_TEMPLATE = '''\
# Generated by pbfuzz_engine.tracers.lldb_batch — do not edit.
import json
import os
import time
import traceback

import lldb

SPEC_PATH = {spec_path}
OUT_PATH = {out_path}

with open(SPEC_PATH) as _f:
    SPEC = json.load(_f)

REPORT = {{
    "breakpoints": [
        {{
            "location": bp["location"],
            "function": None,
            "resolved": None,
            "hit_times": 0,
            "hits": [],
            "number": None,
        }}
        for bp in SPEC["breakpoints"]
    ],
    "signal": None,
    "exit_code": None,
    "errors": [],
    "info_breakpoints": "",
    "flush_count": 0,
}}
_ORDER = [0]
_BY_ID = {{}}

# N2: a plain per-hit flush caps a hot breakpoint at roughly one os.replace()
# syscall per hit. Batching hits into a periodic flush removes that ceiling;
# every non-hot-path transition below still calls _flush(force=True) so
# evidence is never more than one interval stale when the run is killed.
# Value comes from the real pbfuzz_engine.tracers.gdb_batch.FLUSH_INTERVAL_SEC
# constant (formatted in below), not a separately-maintained literal.
_FLUSH_INTERVAL_SEC = {flush_interval}
_LAST_FLUSH_MONO = [0.0]


def _flush(force=False):
    # Write to a temp file in the same directory, then atomically replace the
    # real path (os.replace is a single rename(2) on the same filesystem). A
    # plain `open(OUT_PATH, "w")` truncates in place, so a SIGKILL landing
    # mid-write left a corrupted/empty file; os.replace can only ever leave
    # the OLD complete content or the NEW complete content, never a partial
    # mix. `force=False` throttles this to at most once per
    # _FLUSH_INTERVAL_SEC (N2); callers that need the report to reflect the
    # very latest state right now (breakpoint setup, teardown) pass
    # force=True.
    now = time.monotonic()
    if not force and (now - _LAST_FLUSH_MONO[0]) < _FLUSH_INTERVAL_SEC:
        return
    _LAST_FLUSH_MONO[0] = now
    REPORT["flush_count"] += 1
    tmp_path = OUT_PATH + ".tmp"
    try:
        with open(tmp_path, "w") as fh:
            json.dump(REPORT, fh)
            fh.flush()
        os.replace(tmp_path, OUT_PATH)
    except Exception:
        pass


def _callstack(thread, limit=16):
    lines = []
    for index, frame in enumerate(thread):
        if index >= limit:
            lines.append("  ... (more frames)")
            break
        marker = "*" if index == 0 else " "
        line_entry = frame.GetLineEntry()
        where = frame.GetFunctionName() or "<unknown>"
        if line_entry and line_entry.GetFileSpec():
            where = "%s at %s:%d" % (
                where,
                line_entry.GetFileSpec().GetFilename(),
                line_entry.GetLine(),
            )
        lines.append("%s #%d: %s" % (marker, index, where))
    return "\\n".join(lines)


def on_breakpoint(frame, bp_loc, internal_dict):
    try:
        bp_id = bp_loc.GetBreakpoint().GetID()
        index = _BY_ID.get(bp_id)
        if index is None:
            return False
        spec = SPEC["breakpoints"][index]
        rec = REPORT["breakpoints"][index]
        _ORDER[0] += 1
        rec["hit_times"] += 1
        rec["resolved"] = True
        if rec["function"] is None:
            rec["function"] = frame.GetFunctionName()
        hit = {{"order": _ORDER[0], "callstack": "", "inline_expr": []}}
        # A location lldb accepted may not be where it actually bound: a
        # line with no instruction (blank/comment-only) is silently rebound
        # to the next line that has one. The hit frame's own line entry
        # reports where it *actually* landed, so it can be reported next to
        # the originally requested location instead of masquerading as it.
        line_entry = frame.GetLineEntry()
        file_spec = line_entry.GetFileSpec() if line_entry else None
        if file_spec:
            # GetFilename() alone drops the directory; rebuild the full path
            # (matching the `file:line` shape `bp.location` is written in) so
            # the two are directly comparable.
            directory = file_spec.GetDirectory()
            filename = file_spec.GetFilename()
            full_path = os.path.join(directory, filename) if directory else filename
            hit["resolved_location"] = "%s:%d" % (full_path, line_entry.GetLine())
        if spec.get("print_call_stack"):
            hit["callstack"] = _callstack(frame.GetThread())
        for expr in spec.get("inline_expr") or []:
            value_obj = frame.EvaluateExpression(expr)
            if value_obj is None or value_obj.GetError().Fail():
                reason = value_obj.GetError().GetCString() if value_obj else "no value"
                value = (
                    "<error: %s is not evaluable here (%s). How to fix: "
                    "1. check the variable is in scope at this line "
                    "2. set the breakpoint after the assignment>" % (expr, reason)
                )
            else:
                value = str(value_obj.GetValue() or value_obj.GetSummary() or value_obj)
            hit["inline_expr"].append({{"name": expr, "value": value}})
        rec["hits"].append(hit)
        if rec["hit_times"] >= int(spec.get("hit_limit") or 10):
            bp_loc.GetBreakpoint().SetEnabled(False)
    except Exception:
        REPORT["errors"].append(traceback.format_exc())
    _flush()
    return False  # auto-continue: this is a tracer, not a debugging session


def __lldb_init_module(debugger, internal_dict):
    try:
        debugger.SetAsync(False)
        target = debugger.GetSelectedTarget()
        interp = debugger.GetCommandInterpreter()
        result = lldb.SBCommandReturnObject()
        for command in SPEC.get("pre_run_commands") or []:
            interp.HandleCommand(str(command), result)
        module_name = __name__
        for index, spec in enumerate(SPEC["breakpoints"]):
            bp = target.BreakpointCreateByLocation(str(spec["file"]), int(spec["line"]))
            if bp.GetNumLocations() == 0:
                # Debug info may spell the file differently (relative path,
                # /tmp vs /private/tmp): retry by basename, and say so.
                target.BreakpointDelete(bp.GetID())
                bp = target.BreakpointCreateByLocation(
                    os.path.basename(str(spec["file"])), int(spec["line"])
                )
                if bp.GetNumLocations() > 0:
                    REPORT["errors"].append("bound %s by basename only" % spec["location"])
            _BY_ID[bp.GetID()] = index
            REPORT["breakpoints"][index]["number"] = bp.GetID()
            REPORT["breakpoints"][index]["resolved"] = bp.GetNumLocations() > 0
            bp.SetScriptCallbackFunction("%s.on_breakpoint" % module_name)
    except Exception:
        REPORT["errors"].append(traceback.format_exc())
    _flush(force=True)


def finish():
    """Called after the run so late-binding breakpoints are reported honestly."""
    try:
        debugger = lldb.debugger
        target = debugger.GetSelectedTarget()
        for index, rec in enumerate(REPORT["breakpoints"]):
            number = rec.get("number")
            if number is None:
                continue
            bp = target.FindBreakpointByID(number)
            if bp and bp.IsValid():
                if bp.GetNumLocations() > 0:
                    rec["resolved"] = True
            if rec["hit_times"] > 0:
                rec["resolved"] = True
        process = target.GetProcess()
        if process and process.IsValid():
            state = process.GetState()
            if state == lldb.eStateExited:
                REPORT["exit_code"] = int(process.GetExitStatus())
            else:
                thread = process.GetSelectedThread()
                if thread and thread.GetStopReason() == lldb.eStopReasonSignal:
                    signo = thread.GetStopReasonDataAtIndex(0)
                    REPORT["signal"] = str(
                        process.GetUnixSignals().GetSignalAsCString(signo) or signo
                    )
            process.Kill()
    except Exception:
        REPORT["errors"].append(traceback.format_exc())
    _flush(force=True)
'''


def build_lldb_argv(
    lldb_bin: str, hook_path: str, program: str, args: Sequence[str]
) -> list[str]:
    """Build the ``lldb --batch`` command line for one traced run."""
    module = Path(hook_path).stem
    argv = [
        lldb_bin,
        "--batch",
        "--no-lldbinit",
        "-o",
        f"command script import {hook_path}",
        "-o",
        "run",
        "-o",
        f"script import {module}; {module}.finish()",
        "--",
        program,
    ]
    argv.extend(args)
    return argv


def lldb_python_dir(lldb_bin: str) -> str | None:
    """Return the directory holding lldb's own Python package, or ``None``.

    Asks ``lldb -P`` first. Debian/Ubuntu ``lldb-14`` reports a path that does not exist
    (``/usr/lib/local/lib/python3.X/dist-packages``) while the package lives under the LLVM
    prefix, so fall back to ``<prefix>/lib/python3*/*-packages`` next to the real binary.
    """
    def has_pkg(d: Path) -> bool:
        return (d / "lldb" / "embedded_interpreter.py").is_file()

    try:
        proc = subprocess.run([lldb_bin, "-P"], capture_output=True, text=True, timeout=20)
        reported = Path(proc.stdout.strip().splitlines()[-1]) if proc.stdout.strip() else None
    except (OSError, subprocess.TimeoutExpired):
        reported = None
    if reported is not None and has_pkg(reported):
        return str(reported)
    prefix = Path(os.path.realpath(lldb_bin)).parent.parent
    for cand in sorted(prefix.glob("lib/python3*/*-packages"), reverse=True):
        if has_pkg(cand):
            return str(cand)
    return None


def lldb_env(lldb_bin: str, base: Mapping[str, str]) -> dict[str, str]:
    """``base`` with lldb's Python package directory prepended to ``PYTHONPATH``."""
    env = dict(base)
    pydir = lldb_python_dir(lldb_bin)
    if pydir:
        env["PYTHONPATH"] = os.pathsep.join(p for p in (pydir, env.get("PYTHONPATH", "")) if p)
    return env


class LldbBatchTracer(Tracer):
    """Trace one run with ``lldb --batch``; the fallback where gdb is absent."""

    name = "lldb"
    languages = ("c", "cpp", "other")

    def __init__(self, lldb_path: str = "lldb") -> None:
        self.lldb_path = lldb_path or "lldb"

    def available(self) -> tuple[bool, str]:
        resolved = which(self.lldb_path)
        if not resolved:
            return False, f"`{self.lldb_path}` not found on PATH"
        code, out, err, _ = self._run_process(
            [resolved, "--version"], None, os.environ, 20.0
        )
        first = (out or err).splitlines()[0] if (out or err) else ""
        if code != 0:
            return False, f"`{resolved} --version` exited {code}: {err.strip()[:200]}"
        return True, f"{resolved}: {first}"

    def run(
        self,
        campaign: Mapping[str, Any],
        input_path: str,
        breakpoints: Sequence[Breakpoint],
        timeout_sec: float | None = None,
    ) -> TraceResult:
        lldb_bin = which(self.lldb_path)
        if not lldb_bin:
            raise TracerError(
                f"lldb was not found (`{self.lldb_path}`).",
                [
                    Remedy(
                        id="install_lldb",
                        label="Install lldb",
                        detail="apt-get install lldb",
                        effect="run_command",
                    ),
                    Remedy(
                        id="use_gdb",
                        label="Set campaign `tracer: gdb` instead",
                        effect="edit_campaign",
                    ),
                ],
            )
        bps = self._normalise(breakpoints)
        cmd = build_command(campaign, input_path)

        with tempfile.TemporaryDirectory(prefix="pbfuzz-lldb-") as tmp:
            tmpdir = Path(tmp)
            spec_path = tmpdir / "spec.json"
            out_path = tmpdir / "report.json"
            stderr_path = tmpdir / "target-stderr.txt"
            stderr_path.touch()
            pre_run = [
                "settings set target.error-path " + str(stderr_path),
                "settings set target.output-path " + str(tmpdir / "target-stdout.txt"),
            ]
            if cmd.stdin_path:
                pre_run.append("settings set target.input-path " + cmd.stdin_path)
            spec_path.write_text(
                json.dumps(
                    {
                        "breakpoints": [b.to_spec() for b in bps],
                        "pre_run_commands": pre_run,
                    }
                ),
                encoding="utf-8",
            )
            hook_path = tmpdir / "pbfuzz_lldb_hook.py"
            hook_path.write_text(
                build_lldb_hook(str(spec_path), str(out_path)), encoding="utf-8"
            )
            argv = build_lldb_argv(lldb_bin, str(hook_path), cmd.program, cmd.argv[1:])
            _, _, lldb_stderr, timed_out = self._run_process(
                argv, cmd.cwd, lldb_env(lldb_bin, cmd.env), timeout_sec
            )

            report: dict[str, Any] = {}
            report_decode_error: str | None = None
            if out_path.exists():
                try:
                    report = json.loads(out_path.read_text(encoding="utf-8") or "{}")
                except json.JSONDecodeError as exc:
                    # With the atomic temp-file-then-os.replace flush, this should not
                    # happen for a report this module wrote — but stay defensive for an
                    # old-format or otherwise foreign leftover file, and say so instead
                    # of silently discarding whatever partial evidence was on disk.
                    report = {}
                    report_decode_error = str(exc)
            target_stderr = (
                stderr_path.read_text(encoding="utf-8", errors="replace")
                if stderr_path.exists()
                else ""
            )

        if not report and not timed_out:
            detail = (lldb_stderr or "").strip()[:400] or None
            if report_decode_error:
                prefix = f"report file was present but not valid JSON ({report_decode_error}); "
                detail = prefix + (detail or "")
            raise TracerError(
                "lldb produced no trace report — it failed before the program ran.",
                [
                    Remedy(
                        id="inspect_lldb",
                        label="Run the lldb command by hand to see why",
                        detail=detail,
                        effect="manual",
                    )
                ],
            )
        result = parse_trace_report(report, bps, stderr=target_stderr, timed_out=timed_out)
        result.tracer = "lldb"
        if report_decode_error:
            result.diagnostics.append(
                "lldb's report file existed but was not valid JSON, so it was treated as "
                f"empty (any partial evidence in it was lost): {report_decode_error}"
            )
        if lldb_stderr.strip():
            result.diagnostics.append(f"lldb stderr: {lldb_stderr.strip()[:400]}")
        return result
