#!/usr/bin/env node
/**
 * Bundle src/client/ into ONE self-contained lib/client.js and self-check it.
 *
 * DSH loads a plugin's client.js as a CLASSIC <script> (dsh-client-modules), so the
 * file must contain no top-level import/export/require and must hand its body to
 * `window.__ModuleLoader__.load({ id, factory })`. The loader later calls
 * `factory(require)` with a require bound to the platform module table.
 *
 * Output shape (identical to DSH's own tsdown.client.ts preset and W6's pbfuzz bundle):
 *   window.__ModuleLoader__.load({ id: "<pkg name>", factory: (require) => {
 *   var module = { exports: {} }; var exports = module.exports;
 *   ...esbuild CJS body; externals are plain require("react") calls...
 *   return module.exports; } });
 *
 * esbuild: format 'cjs', bundle: true, wrapped in that closure. The file is a
 * classic-safe script whose only top-level statement is the load() call. Every
 * require() resolves through the factory's `require` parameter; there is never a
 * global require. Not format 'iife': its `__require` shim throws "Dynamic require
 * ... not supported" wherever no require is lexically in scope, so the self-check
 * rejects that shim outright. Platform modules stay external and everything else is
 * inlined. Any other @deepseek-ai VALUE import fails the build, mirroring DSH's
 * bundle purity gate; type-only imports are erased and never reach it.
 *
 * Usage: node scripts/build-client.mjs   (build, then self-check; exit 1 on failure)
 */
import { build } from 'esbuild'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))
const outfile = resolve(root, 'lib/client.js')

/**
 * The shell's frozen module table (deepseek-harness packages/client/web/src/platform.ts,
 * PLATFORM_MODULES at the pinned HARNESS_COMMIT). Only these may stay external.
 */
const PLATFORM_MODULES = [
  'react', 'react/jsx-runtime', 'react-dom', 'react-dom/client', '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

/** Build-time mirror of DSH's client bundle purity gate. */
const purity = {
  name: 'dsh-client-bundle-purity',
  setup(b) {
    b.onResolve({ filter: /^@deepseek-ai\// }, (args) => {
      if (PLATFORM_MODULES.includes(args.path)) return { path: args.path, external: true }
      return {
        errors: [{
          text: `client bundle purity: "${args.path}" is not a platform module — cross-plugin value imports are forbidden `
            + '(use `import type` and collaborate through cordis services)',
        }],
      }
    })
  },
}

const result = await build({
  entryPoints: [resolve(root, 'src/client/index.ts')],
  outfile,
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  jsx: 'automatic',
  jsxImportSource: 'react',
  external: PLATFORM_MODULES,
  plugins: [purity],
  define: { 'process.env.NODE_ENV': '"production"' },
  legalComments: 'inline',
  charset: 'utf8',
  minify: false,
  metafile: true,
  logLevel: 'warning',
  banner: {
    js: `/* ${pkg.name} v${pkg.version} client bundle — generated by scripts/build-client.mjs from src/client/; do not edit. */\n`
      + `window.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: (require) => {\n`
      + 'var module = { exports: {} }; var exports = module.exports;',
  },
  footer: { js: 'return module.exports; } });' },
})

// ---- self-check -----------------------------------------------------------

const out = readFileSync(outfile, 'utf8')
const fail = (msg) => {
  console.error(`✗ lib/client.js self-check: ${msg}`)
  process.exit(1)
}

// 1. Parses as a CLASSIC script: any import/export statement is a SyntaxError here.
try {
  new vm.Script(out, { filename: 'client.js' })
} catch (error) {
  fail(`not a valid classic script (${error.message})`)
}
// Belt and braces: no statement-position import/export lines at all.
if (/^\s*import[\s{*]/m.test(out)) fail('contains a top-level import statement')
if (/^\s*export[\s{*]/m.test(out)) fail('contains a top-level export statement')
if (!out.includes('window.__ModuleLoader__.load(')) fail('missing window.__ModuleLoader__.load(...) call')
// The esbuild IIFE/ESM external shim throws at runtime outside a require scope.
if (out.includes('Dynamic require of')) fail('contains esbuild\'s "Dynamic require" shim — externals must be plain CJS require() calls')
if (!out.trimEnd().endsWith('return module.exports; } });')) fail('factory does not return module.exports')

// 2. Executing the script only registers the factory: no global require is touched.
const registrations = []
const sandbox = { window: { __ModuleLoader__: { load: (r) => { registrations.push(r) } } }, console }
try {
  vm.runInNewContext(out, sandbox, { filename: 'client.js' })
} catch (error) {
  fail(`top-level execution threw (a top-level require/import leaked?): ${error.message}`)
}
if (registrations.length !== 1) fail(`expected exactly one __ModuleLoader__.load call, saw ${registrations.length}`)
const [reg] = registrations
if (reg.id !== pkg.name) fail(`registration id ${JSON.stringify(reg.id)} != package name ${JSON.stringify(pkg.name)}`)
if (typeof reg.factory !== 'function') fail('registration has no factory function')

// 3. Materialize with a stub module table: every require must be a platform module,
//    and the exports must be a cordis plugin face.
const requested = new Set()
const stub = () => new Proxy(function stubModule() {}, {
  get: (_t, prop) => (prop === '__esModule' || prop === 'default' || typeof prop === 'symbol' ? undefined : stub()),
})
let exported
try {
  exported = reg.factory((spec) => {
    requested.add(spec)
    if (!PLATFORM_MODULES.includes(spec)) throw new Error(`require of non-platform module "${spec}"`)
    return stub()
  })
} catch (error) {
  fail(`factory threw on materialization: ${error.message}`)
}
if (exported === null || typeof exported !== 'object') fail('factory did not return an exports object')
if (typeof exported.apply !== 'function') fail('exports.apply is not a function')
if (!Array.isArray(exported.inject) || !exported.inject.includes('settingsScope')) fail('exports.inject is missing or incomplete')

// 4. Statically: every literal require in the file names a platform module.
for (const m of out.matchAll(/\brequire\(\s*["']([^"']+)["']\s*\)/g)) {
  if (!PLATFORM_MODULES.includes(m[1])) fail(`literal require("${m[1]}") is not a platform module`)
}

const inputs = Object.keys(result.metafile.inputs).length
const kb = (out.length / 1024).toFixed(1)
console.log(`✔ lib/client.js ${kb} kB ← ${inputs} source files; classic-safe; one __ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)} })`)
console.log(`  externals required at materialization: ${[...requested].sort().join(', ') || '(none)'}`)
console.log(`  exports: apply(), inject = [${exported.inject.join(', ')}]`)
