#!/usr/bin/env node
/**
 * Generate TypeScript types, plus a Python schema-file loader, from `contracts/*.schema.json`.
 *
 * The contracts are the one source of truth shared by the TS plugins, the Python engine and the
 * hook scripts; generating both faces from them is what keeps a schema change from silently
 * skewing one side. Generated files are COMMITTED so a git install needs no codegen step.
 *
 * The Python side (`generatePython()` below) does NOT emit pydantic models — it emits
 * `generated/contracts.py`, a small loader (`load_schema()` + `SCHEMA_FILES`) that reads the
 * schema files at runtime. `campaign.py` validates campaigns by hand rather than through it.
 *
 * Usage:
 *   node scripts/codegen.mjs           regenerate in place
 *   node scripts/codegen.mjs --check   fail (exit 1) if the committed output is stale
 */

import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const contractsDir = join(root, 'contracts')
const check = process.argv.includes('--check')

/** Every `*.schema.json` under contracts/, recursively, as repo-relative paths. */
async function schemaFiles(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await schemaFiles(full))
    else if (entry.name.endsWith('.schema.json')) out.push(full)
  }
  return out.sort()
}

/** Write `content` to `file`, or in --check mode report whether it would change. */
async function emit(file, content, stale) {
  const existing = existsSync(file) ? await readFile(file, 'utf8') : null
  if (existing === content) return
  if (check) {
    stale.push(relative(root, file))
    return
  }
  await mkdir(dirname(file), { recursive: true })
  await writeFile(file, content)
  console.log(`  wrote ${relative(root, file)}`)
}

/**
 * Delete `file` if a previous codegen run left it behind but the current scoping no longer
 * emits it there (e.g. `analysis-provider.ts` used to be copied into dsh-kanalyzer's
 * `generated/` and no longer is). In --check mode this reports it as stale instead of deleting.
 */
async function removeStale(file, stale) {
  if (!existsSync(file)) return
  if (check) {
    stale.push(relative(root, file))
    return
  }
  await rm(file)
  console.log(`  removed ${relative(root, file)}`)
}

const BANNER_TS = '// GENERATED by scripts/codegen.mjs from contracts/*.schema.json — do not edit.\n'
  + '// Run `pnpm codegen` after changing a contract.\n\n'
const BANNER_PY = '# GENERATED by scripts/codegen.mjs from contracts/*.schema.json — do not edit.\n'
  + '# Run `pnpm codegen` after changing a contract.\n\n'

/**
 * Build the TS declarations for `files`. json-schema-to-typescript is a devDependency; when it
 * is not installed (a fresh checkout that has not run `pnpm install`) this reports that rather
 * than pretending to succeed, because a stale generated file is worse than a missing one.
 *
 * Callers pass a SUBSET of the full schema list to scope the output to one consuming package —
 * see the two call sites below. `banner` lets a scoped call say what it was scoped to.
 */
async function generateTypes(files, banner = BANNER_TS) {
  let compile
  try {
    ({ compile } = await import('json-schema-to-typescript'))
  } catch {
    console.error('json-schema-to-typescript is not installed — run `pnpm install` first.')
    process.exit(2)
  }
  const chunks = []
  for (const file of files) {
    const schema = JSON.parse(await readFile(file, 'utf8'))
    chunks.push(await compile(schema, schema.title ?? 'Schema', {
      cwd: dirname(file),
      bannerComment: '',
      additionalProperties: false,
      declareExternallyReferenced: true,
      style: { semi: false, singleQuote: true },
    }))
  }
  return banner + chunks.join('\n')
}

/**
 * Build `generated/contracts.py` — NOT pydantic models. It is a schema-file loader
 * (`load_schema()` + `SCHEMA_FILES`) that lets the engine read a contract schema by name at
 * runtime; nothing here parses the schema into Python classes. `campaign.py` validates
 * `pbfuzz.campaign.yaml` by hand.
 *
 * The schema directory comes from `_contracts_dir.py` (hand-written, NOT generated, a sibling
 * of `generated/` under `engine/pbfuzz_engine/`), which resolves `$PBFUZZ_CONTRACTS_DIR` first
 * and falls back to the repo-relative default — the same convention a hook-style Python tree
 * would use. Keeping that logic out of this generated file means a `pnpm codegen` run can never
 * silently discard it.
 */
async function generatePython(files) {
  const lines = [
    BANNER_PY,
    'from __future__ import annotations',
    '',
    'import json',
    'from typing import Any',
    '',
    'from .. import _contracts_dir',
    '',
    'CONTRACTS_VERSION = "1"',
    '',
    '_SCHEMA_DIR = _contracts_dir.schema_dir()',
    '',
    '',
    'def load_schema(name: str) -> dict[str, Any]:',
    '    """Return one contract schema by file name, e.g. `campaign.schema.json`."""',
    '    return json.loads((_SCHEMA_DIR / name).read_text())',
    '',
    '',
    'SCHEMA_FILES: tuple[str, ...] = (',
    ...files.map(f => `    ${JSON.stringify(relative(contractsDir, f))},`),
    ')',
    '',
  ]
  return lines.join('\n')
}

/**
 * The two hand-written TS interface contracts are not JSON Schema, so they are copied verbatim
 * into `generated/` rather than restated by hand (a restatement drifts silently). Their
 * `./generated/types.ts` import is rewritten to the sibling generated file.
 *
 * `kanalyzer-api.ts` is copied into BOTH packages: kanalyzer implements it, pbfuzz consumes it
 * (and `contract-parity.spec.ts` checks the two stay identical). `analysis-provider.ts` is
 * pbfuzz's OWN internal auxiliary-analysis provider interface — it imports `PbfuzzCampaign` and
 * has no meaning to a standalone kanalyzer install, so it is copied into `dsh-pbfuzz` only.
 * Shipping it into `dsh-kanalyzer` is exactly the "kanalyzer knows about pbfuzz" leak this
 * function must not reintroduce.
 */
async function copyTsContracts(stale) {
  const targets = {
    'kanalyzer-api.ts': ['dsh-pbfuzz', 'dsh-kanalyzer'],
    'analysis-provider.ts': ['dsh-pbfuzz'],
  }
  for (const [name, pkgs] of Object.entries(targets)) {
    const src = (await readFile(join(contractsDir, name), 'utf8'))
      .replaceAll("'./generated/types.ts'", "'./contracts.ts'")
    const body = BANNER_TS.replace('*.schema.json', name) + src
    for (const pkg of pkgs) {
      await emit(join(root, 'packages', pkg, 'src', 'generated', name), body, stale)
    }
  }
}

const POLICY_BANNER_TS = '// GENERATED by scripts/codegen.mjs from contracts/policy.json — do not edit.\n'
  + '// Run `pnpm codegen` after changing a contract.\n\n'

/**
 * `contracts/policy.json` is not a JSON Schema (deliberately: the type generator above only
 * looks at `*.schema.json`) but a small shared table — the self-check gate, the phase→tool map
 * and the tool→backing-item map — that `core/phases.ts` (tool visibility) and
 * `core/guard-policy.ts` (in-process enforcement) both read, so the two engines that used to be
 * TS and Python can't drift from each other now that there is only one engine.
 */
async function readPolicy() {
  return JSON.parse(await readFile(join(contractsDir, 'policy.json'), 'utf8'))
}

/** TS: one `as const` object literal, so every nested value keeps its literal type. */
function generatePolicyTs(policy) {
  return POLICY_BANNER_TS + `export const POLICY = ${JSON.stringify(policy, null, 2)} as const\n`
}

const files = await schemaFiles(contractsDir)
console.log(`codegen: ${files.length} schema(s)`)
const stale = []

// dsh-pbfuzz drives the whole system, so it gets the full type surface: campaign, state,
// pbfuzz-settings, kanalyzer-settings, everything.
const ts = await generateTypes(files)
await emit(join(contractsDir, 'generated', 'types.ts'), ts, stale)
await emit(join(root, 'packages', 'dsh-pbfuzz', 'src', 'generated', 'contracts.ts'), ts, stale)

// dsh-kanalyzer "knows nothing about pbfuzz" (contracts/README.md): it must NOT ship
// PbfuzzCampaign/PbfuzzState/etc. Scope its contracts.ts to only the schema(s) its own source
// actually imports (today: KanalyzerSettings, from kanalyzer-settings.schema.json — see
// `src/host/settings.ts`, `src/client/controller.ts`, `src/client/index.ts`). Adding a schema
// kanalyzer needs means adding its file name here, not widening this to the full `files` list.
const KANALYZER_SCHEMAS = ['kanalyzer-settings.schema.json']
const kanalyzerFiles = files.filter(f => KANALYZER_SCHEMAS.includes(relative(contractsDir, f)))
const kanalyzerBanner = BANNER_TS.replace(
  '*.schema.json',
  `{${KANALYZER_SCHEMAS.join(', ')}} (scoped — dsh-kanalyzer knows nothing about pbfuzz)`,
)
const kanalyzerTs = await generateTypes(kanalyzerFiles, kanalyzerBanner)
await emit(join(root, 'packages', 'dsh-kanalyzer', 'src', 'generated', 'contracts.ts'), kanalyzerTs, stale)

await emit(join(root, 'engine', 'pbfuzz_engine', 'generated', 'contracts.py'), await generatePython(files), stale)
await copyTsContracts(stale)

// Cleanup: files an earlier, unscoped codegen left in dsh-kanalyzer's generated/ that this
// version no longer emits there. Without this, a stale file from before this fix would keep
// shipping even though nothing regenerates it.
await removeStale(join(root, 'packages', 'dsh-kanalyzer', 'src', 'generated', 'analysis-provider.ts'), stale)

const policy = await readPolicy()
await emit(join(root, 'packages', 'dsh-pbfuzz', 'src', 'generated', 'policy.ts'), generatePolicyTs(policy), stale)

if (check && stale.length > 0) {
  console.error(`\ncodegen is stale — run \`pnpm codegen\` and commit:\n  ${stale.join('\n  ')}`)
  process.exit(1)
}
console.log('codegen: ok')
